 version: "3.6"
 services:
   gitlab:
     image: gitlab/gitlab-ce:12.8.2-ce.0
     ports:
       - "222:22"
       - "8090:80"
       - "8443:443"
     volumes:
       - /srv/gitlab/data:/var/opt/gitlab
       - /srv/gitlab/logs:/var/log/gitlab
       - /srv/gitlab/config:/etc/gitlab
     environment:
       GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
     configs:
       - source: gitlab
         target: /omnibus_config.rb
     secrets:
       - gitlab_root_password
   #gitlab-runner:
    # image: gitlab/gitlab-runner:alpine
     #volumes:
      # - /srv/gitlab/gitlab-runner:/etc/gitlab-runner
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /root/.m2:/root/.m2
     #deploy:
      # mode: replicated
       #replicas: 1
 configs:
   gitlab:
     file: ./gitlab.rb
 secrets:
   gitlab_root_password:
     file: ./root_password.txt
