version: '3.7'

services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    deploy:
      restart_policy:
        condition: on-failure
    environment:
     MYSQL_ROOT_PASSWORD: rYa+wq10dFTWzYz8FeZgsWRygyKfLKULSRdKfRnEgSk=
    volumes:
      - /mnt1/mysql/mysql8:/var/lib/mysql
      - /mnt1/mysql/mysql8_conf:/etc/mysql
    ports:
      - "3309:3306"
