version: '3.7'

services:

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - data-mysql:/var/lib/mysql
      - config-mysql:/etc/mysql
    ports:
      - "3306:3306"
volumes:
  data-mysql:
  config-mysql:
