version: '3.7'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - data-mysql:/var/lib/mysql
    ports:
      - "3308:3306"
volumes:
  data-mysql:
