FROM redis
RUN /bin/bash -c 'source $HOME/.bashrc; \
echo $HOME'
CMD ["/bin/bash","-c","ehco 1"]
CMD ["/bin/bash","-c","ehco 1"]
LABEL "com.example.vendor"="ACME Incorporated"
LABEL com.example.label-with-value="foo"
LABEL version="1.0"
LABEL description="This text illustrates \
that label-values can span multiple lines."
