version: '3.7'

services:

  mongo:
    image: mongo
    deploy:
      restart_policy:
        condition: on-failure
    command: --bind_ip_all
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: junyang@2019
    volumes:
      - data-mongo:/data/db


  mongo-express:
    image: mongo-express
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: junyang@2019
volumes:
  data-mongo:

