version: "3.7"
services:
  redis:
    image: redis:4.0.11-alpine
    volumes:
      - data-redis:/data
    ports:
      - "6388:6379"
    networks:
      - redisnet
networks:
  redisnet:
volumes:
  data-redis:
